version: '3.8'

services:

  mysql-order:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: order_db
    volumes:
      - mysql_order_data:/var/lib/mysql

  mysql-inventory:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: inventory_db
    volumes:
      - mysql_inventory_data:/var/lib/mysql

  order-service:
    build: ./order-service
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://mysql-order:3306/order_db?allowPublicKeyRetrieval=true&useSSL=false
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
    depends_on:
      - mysql-order

  inventory-service:
    build: ./inventory-service
    ports:
      - "8081:8081"
    environment:
      - DB_URL=jdbc:mysql://mysql-inventory:3306/inventory_db?allowPublicKeyRetrieval=true&useSSL=false
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
    depends_on:
      - mysql-inventory

volumes:
  mysql_order_data:
  mysql_inventory_data:
